### ISSUE TITLE
TCP Reno protocol simulation feature required.

### ISSUE THREAD

**Issue by TejasVKolhe** [TejasVKolhe/SE_LabAssignments#2]
We need to implement a simulation of the TCP Reno protocol in our project. The primary goal of this feature is to accurately model TCP Reno's behavior under various conditions, especially focusing on how it responds to packet loss.

**Comment by khedkarsayali** [comment]
Issue Resolved! TCP Reno implementation added , packet loss and congestion window resizing handled.

**Comment by TejasVKolhe** [comment]
Feature added, TCP Tahoe and TCP Reno now provided with java codes too.
